[package]
name = "slow-repin-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tree-sitter = "0.20.9"
tree-sitter-highlight = "0.20"
